### ISSUE TITLE
ETA for code release?

### ISSUE THREAD

**Issue by zcdliuwei** [skhu101/SHERF#1]
Hi, thanks for this amazing work and I really can't wait to try this out!! Is there an estimated date for the code release? 

In addition, I have a question to ask,
Is it possible to replace a real person with an animation character, and then use dance videos to drive the animation character to dance
Thanks a lot :)

**Comment by hengfei-wang** [comment]
Waiting for the code +1

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. We will release the code upon the acceptance of the paper. I will test the code with a real person image and send the feedback to you.

**Comment by zcdliuwei** [comment]
> 

Thanks again！！

**Comment by louhz** [comment]
Hi, I am just curious about the release schedule for this codebase.
I heard from Professor Ziwei Liu that this codebase will be released by mid of May.
What's the progress right now!
Thanks

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. We are currently preparing the code and will release the code upon paper acceptance.

**Comment by skhu101** [comment]
> 
Hi, thanks for your insightful question regarding the generalization performance of SHERF. We test the SHERF with a real person image from DeepFashion and show the results as follows. 

![MEN-Denim-id_00000089-04_7_additional_512x512](https://github.com/skhu101/SHERF/assets/62331757/3b0e5f0f-d2e2-490f-8e10-1399f4ae82b7)

https://github.com/skhu101/SHERF/assets/62331757/371faae3-0b3b-4f66-9384-bd61a952f3aa


https://github.com/skhu101/SHERF/assets/62331757/13a01d54-55be-4745-b6c6-4480a87037ab

**Comment by skhu101** [comment]
Hi, thanks for your interest. Just let you know we have released the code. Hope you enjoy it.
