### ISSUE TITLE
Bug while testing on HuMMan dataset

### ISSUE THREAD

**Issue by scnuhealthy** [skhu101/SHERF#10]
I follow the guidance, but a bug appears in test_loop.py line 210
```img = np.concatenate([input_img_resize, img], axis=0) ```
the size of ```input_img_resize``` is (720,720,3) while ```img``` is (360,1280,3)

**Comment by skhu101** [comment]
Hi, thanks for your reminder. You can change "img = np.concatenate([input_img_resize, img], axis=0) " to "input_img_resize = cv2.resize(input_img, (2*W, H))". I have updated the test code. If you have any further questions, please let me know.

**Comment by scnuhealthy** [comment]
Thanks for your reply. And I found another bug in ```HuMMan_dataset.py```  , ```obs_view_index``` is not defined while testing. One solution maybe ```obs_view_index=self.obs_view_index```

**Comment by skhu101** [comment]
Hi, may I ask in which line do you have the error? By the way, do you use the latest code in HuMMan_dataset.py?

**Comment by scnuhealthy** [comment]
The line 340 ```obs_view_index``` is not defined, I think it should be self.obs_view_index

**Comment by skhu101** [comment]
Hi,  I have fixed the code. Now it should work. Thanks for pointing out this.
