### ISSUE TITLE
Installing Dependencies Error

### ISSUE THREAD

**Issue by StephenYangjz** [skhu101/SHERF#11]
Greetings,

I am having issues with installing dependencies using requirement.txt. The format is somehow not being recognized as correct and it can't find anything, as attached:

```
conda create --name sher --file requirement.txt 
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - jedi==0.18.2=pypi_0
  - olefile==0.46=pyh9f0ad1d_1
  - pyglet==2.0.7=pypi_0
  ...
  ```
And,

```
pip install -r requirement.txt
ERROR: Invalid requirement: '_libgcc_mutex=0.1=main' (from line 2 of requirement.txt)
Hint: = is not a valid operator. Did you mean == ?`
```
It would be great if I may get some help on this. Thank you! @skhu101

**Comment by skhu101** [comment]
Hi, thanks for pointing out this. I have updated the dependency file requirement.txt. Now you could install the conda environment successfully. If you have any other questions, please do not hesitate to let me know.
