### ISSUE TITLE
Dataset Preparation For Inference

### ISSUE THREAD

**Issue by StephenYangjz** [skhu101/SHERF#12]
Greetings,

I am wondering if it's possible to do 1) inference on ZJU Mocap dataset, since the command script is not provided and 2) how is the dataset for THUman prepared? I see the flag --data=data/THuman/nerf_data_/results_gyc_20181010_hsc_1_M but I can not seem to find the corresponding folder in the original THUman dataset.

Thank you!

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. 1) I will soon release the pre-trained checkpoint of SHERF on ZJU Mpcap dataset. 2) I use the THuman dataset processed by authors of MPS-NeRF. You can follow the instructions of https://github.com/gaoxiangjun/MPS-NeRF to download the processed THuman dataset.

**Comment by skhu101** [comment]
Hi, just let you know the pre-trained checkpoint of SHERF on ZJU Mocap dataset has been released.
