### ISSUE TITLE
the problem about the dataset downloading

### ISSUE THREAD

**Issue by bing-stu** [skhu101/SHERF#14]
Hi, would you like to tell me the process for downloading the HuMMan dataset? Because I have found three choice in "https://caizhongang.github.io/projects/HuMMan/recon.html:,such as "Part 1: [Aliyun ]...","Part 2: [Aliyun ]...", and "Part 3: [Aliyun ]...". Thanks for your reply.

**Comment by skhu101** [comment]
Hi, all three zipped files are needed.
