### ISSUE TITLE
Preparation with THUman Dataset

### ISSUE THREAD

**Issue by tommycwh** [skhu101/SHERF#16]
Thank you very much for your work! I would like to train SHERF on THUman dataset. If I am understanding it correctly, it requires generating images from multiple views for each person in the dataset, but I am not clear about how to generate these data using your code. Would you mind giving me more hints on how to do this?

Thanks again!

**Comment by skhu101** [comment]
Hi, we use rendered multi-view images of THUman from MPS-NeRF. You can directly download the multi-view images from the link we provide.

**Comment by tommycwh** [comment]
I see. I misunderstood that there are another dataset generated for SHERF. Thank you for your prompt reply.
