### ISSUE TITLE
Preprocessing code for a custom video dataset

### ISSUE THREAD

**Issue by Oocean35** [skhu101/SHERF#17]
Hi @skhu101 , 
Thanks a lot for sharing this very insightful work ! 
It would be really great if you could provide the code that one can use to prepare one's own video dataset to use for training ! 
This would be incredibly helpful ! 
Thanks a lot !

**Comment by skhu101** [comment]
Hi, I think for the video dataset, you need to first estimate the camera and SMPL parameters. Maybe one possible solution is to use CLIFF (CLIFF: Carrying Location Information in Full Frames into Human Pose and Shape Estimation). Then you can follow our RenderPeople dataloader to train the model.
