### ISSUE TITLE
THuman Dataset Loading Error 

### ISSUE THREAD

**Issue by infusion-zero-edit** [skhu101/SHERF#19]
the THuman dataset file expects 'annots.npy' in the data root but there is no Thuman Dataset which contains this file. Please provide the correct data loader for THuman Dataset. 

ann_file = os.path.join(data_root, 'annots.npy')

**Comment by infusion-zero-edit** [comment]
Can anybody please reply on this ?

**Comment by infusion-zero-edit** [comment]
There is a need to correct the file for Thuman Dataset ? can you please update the file for this ?

**Comment by skhu101** [comment]
Hi, we use THuman data set processed by MPS-NeRF. You can send an email to authors of MPS-NeRF to download it.

**Comment by infusion-zero-edit** [comment]
Request you to please give the link for the preprocessed dataset or please share the preprocess script or update the dataloader we are blocked on this for comparing your model

**Comment by skhu101** [comment]
Hi, I have checked with MPS-NERF authors and they say they have shared rendered multi-view images to you. Could you please have a check by sending an email to the first author of MPS-NERF? Our code requires rendered multi-view images to run it.

**Comment by infusion-zero-edit** [comment]
HI, thanks a ton it works !!
