### ISSUE TITLE
Multiple frames per subject during training?

### ISSUE THREAD

**Issue by pansanity666** [skhu101/SHERF#2]
Hi, 
    It seems that multiple frames for each subject is required during training since the target view is different from the input view in Fig. 2. Did you try one frame per subject during training?

**Comment by skhu101** [comment]
Hi, we currently use multiple frames (different poses) for each subject during training as we hope to recover the 3D human in the canonical space. It is interesting to try only using one frame (pose) per subject during training.

**Comment by skhu101** [comment]
Hi, we randomly sample one target and one input camera view from the same pose of the same subject to construct the pair data during training.
