### ISSUE TITLE
THuman dataset from MPS-NeRF seems not include 'new_params_neutral'

### ISSUE THREAD

**Issue by pansanity666** [skhu101/SHERF#25]
Hi, 

I am trying to run the training code on THuman. However, this line https://github.com/skhu101/SHERF/blob/866a750847d6efd43fcc9f18373f68fe6b85f67d/sherf/training/THuman_dataset.py#L239C31-L239C31 seems to load smpl params from 'new_params_neutral' folder. 
 However, for each subject from the MPS-NeRF processed dataset, it only contain 'new_params' folder. Is there anything wrong? 

Best,

**Comment by skhu101** [comment]
Hi, thanks for your interest. You can download the new_params_neutral from https://mycuhk-my.sharepoint.com/:u:/g/personal/1155098117_link_cuhk_edu_hk/ESgPK9M9zNxPr3dqEAoao4gBsomBTbAakC4c6eCpNxGGZA?e=i9wZni.

**Comment by pansanity666** [comment]
Thx
