### ISSUE TITLE
Self_data run

### ISSUE THREAD

**Issue by Danbinabo** [skhu101/SHERF#26]
How to produce multi-angle and multi-pose on any pedestrian image provided by ourselves?

**Comment by skhu101** [comment]
Hi, for a pedestrian image, you need to first estimate the camera and SMPL parameters. Maybe one possible solution is to use CLIFF (CLIFF: Carrying Location Information in Full Frames into Human Pose and Shape Estimation). Then you can follow our RenderPeople dataloader to render results with different angles and different poses.
