### ISSUE TITLE
StyleGAN Not Pre-Trained?

### ISSUE THREAD

**Issue by GloryyrolG** [skhu101/SHERF#29]
Hi @skhu101 et al.,

Thank you for your good contribution. May I ask if it is correct that the StyleGAN component of Tri-Plane is trained from scratch?

https://github.com/skhu101/SHERF/blob/9f360fc49ef6d659ddf63001d1e0b08b2fd2de29/sherf/training/triplane.py#L59

Thx & Rgds,

**Comment by skhu101** [comment]
Yes, we train Tri-Plane from scratch.
