### ISSUE TITLE
Ruquirement for GPU?

### ISSUE THREAD

**Issue by greatbaozi001** [skhu101/SHERF#3]
thanks for your excellent work! I want to know what GPU you used for traing and how long did you spend for training. Hope for your reply!

**Comment by skhu101** [comment]
Hi, thanks for your interest in our paper. We use NVIDIA Tesla V100 GPU cards to train the model. It takes about 36~48 total GPU hours to get acceptable results on 4 GPU cards.

**Comment by greatbaozi001** [comment]
Thanks for your reply! Do you mean that training takes about 36~48 hours on 4 Tesla V100, or just 9~12 hours?

**Comment by skhu101** [comment]
Yes, it takes about takes about 36~48 hours on 4 Tesla V100. During our experiments, we find running SHERF on 4 Tesla V100 for a day can get somewhat reasonable results.

**Comment by greatbaozi001** [comment]
OK! thank you!

**Comment by greatbaozi001** [comment]
OK! thank you!
