### ISSUE TITLE
No (I-) LBS Offset?

### ISSUE THREAD

**Issue by GloryyrolG** [skhu101/SHERF#30]
Hi @skhu101 ,

May I check if (I-) LBS offset was observed to bring minor improvement given it is not applied?
https://github.com/skhu101/SHERF/blob/9f360fc49ef6d659ddf63001d1e0b08b2fd2de29/sherf/training/volumetric_rendering/renderer.py#L567

Thx & Rgds,

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. We did not try adding LBS offset module in our experiments. One concern is that the LBD offset module may not have strong generalization ability.
