### ISSUE TITLE
Visibility Calc

### ISSUE THREAD

**Issue by GloryyrolG** [skhu101/SHERF#33]
Hi @skhu101 @hongfz16 et al.,

May I ask if the calculation of vertex visibilities has a reference and is correct? Thx & best,

https://github.com/skhu101/SHERF/blob/9f360fc49ef6d659ddf63001d1e0b08b2fd2de29/sherf/training/volumetric_rendering/renderer.py#L695

![image](https://github.com/skhu101/SHERF/assets/33202229/46a024a9-c0f5-4a45-8f6d-8a434f46fc90)

**Comment by skhu101** [comment]
Yes, you are right. We use the normal of SMPL vertices as a reference.
