### ISSUE TITLE
The dimension of sampled features

### ISSUE THREAD

**Issue by yankainan** [skhu101/SHERF#35]
Thanks for your excellent work! I would like to ask, what does the dimension '3' represent in the 'sampled_features' within the 'run_model' function, where the dimension of the sampled_features is [bs, 3, sampled points number, 32]?

**Comment by skhu101** [comment]
Hi, the 3 represents three different features, i.e., 1d global feature, 2d pixel aligned feature, and 3d point-based feature.

**Comment by yankainan** [comment]
> Hi, the 3 represents three different features, i.e., 1d global feature, 2d pixel aligned feature, and 3d point-based feature.

OK! thank u for your reply!
