### ISSUE TITLE
styleGAN2 pretrained model

### ISSUE THREAD

**Issue by ax0057** [skhu101/SHERF#36]
Hi, thanks for your brilliant work. I'm trying to retrain the network and I wonder if I can use styleGAN2 pretrained model to initialize the GAN backbone?

**Comment by skhu101** [comment]
Yes, but I am unsure whether the dimensions are the same as the styleGAN2 backbone or not.

**Comment by ax0057** [comment]
Thank you for replying! May I ask you about the gpus you used for training and how long does it take to retrain your network? 😊

**Comment by skhu101** [comment]
Hi, we use 4 V100 GPU for training, which takes about 1~2 days to converge.

**Comment by ax0057** [comment]
Got it😆! Thank you so much.
