### ISSUE TITLE
Difference between new_params_neutral and new_params

### ISSUE THREAD

**Issue by greatbaozi001** [skhu101/SHERF#37]
Hellow! In the Thuman dataset, it seems that one can generate SMPL vertices by either loading from `new_verttices` or calculating from `new_params_neutral` or `new_params`. What's the different among these three kind of method for loading SMPL vertices?

**Comment by skhu101** [comment]
Hi, new_params are estimated for male or female gender, while new_params_neutral are estimated for neutral gender.

**Comment by skhu101** [comment]
Hi, parameters in SMPL models with different genders are different. So the generated vertices have a tiny difference.

**Comment by greatbaozi001** [comment]
Sorry that I am still a kind of confused. 
Now I realize that the difference between `new_params` and `new_params_neutral` are different as they are estimated for male / female gender or neutral gender.
I wonder how the `new_vertices` were calculated, as I found that there is a slightly difference between `new_vertices` and the one calculated from either `new_params` or `new_params_neutral`.
