### ISSUE TITLE
Testing code for DeepFashion

### ISSUE THREAD

**Issue by tingyulan** [skhu101/SHERF#38]
Firstly, thank you for the amazing work!

I noticed that you've tested SHERF with a real person image from DeepFashion. Would it be possible for you to share the testing code and instructions for that? Thank you!

**Comment by tingyulan** [comment]
I have successfully reproduced something similar. I will be closing this issue.

**Comment by shit6333** [comment]
Hi, I have the same problem with this. Could you tell me how you implemented it?
