### ISSUE TITLE
The time for releasing the code

### ISSUE THREAD

**Issue by bing-stu** [skhu101/SHERF#5]
Hi, thanks for your greatful work for view synthesis. I want to know when would you like to release the code? Thank you for your reply.

**Comment by skhu101** [comment]
Hi, thanks for your interest in our paper. We are now preparing the code and plan to release the code this month.

**Comment by bing-stu** [comment]
Hi, would you prepare to release the code today in 31 July, Or there is some other release schedule? Thank you for your reply.

**Comment by skhu101** [comment]
Hi, thanks for your interest. Just let you know we have released the code. Hope you enjoy it.
