### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by belgacemi** [skhu101/SHERF#7]
@skhu101 ! Congratulations on the acceptance of your paper for ICCV 2023!
Could you please share the release schedule for the project ? 
Thanks a lot !

**Comment by skhu101** [comment]
Hi, thanks for your interest in our paper. We are now preparing the code and plan to release the code this month.

**Comment by skhu101** [comment]
Hi, thanks for your interest. Just let you know we have released the code. Hope you enjoy it.
