### ISSUE TITLE
Setting for testing

### ISSUE THREAD

**Issue by greatbaozi001** [skhu101/SHERF#8]
Hello, I would like to know the scheme of testing. 
For novel view synthesis, which view is sampled as input view, and which views are sampled as output views?
For novel pose synthesis, which pose is sampled as input pose, and which poses are sampled as output poses?

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. For each dataset, we take one view from 3 views (e.g., front view, back view and side view) as the input view and all other views serve as output views. Then we average the performance of three input views.
For novel pose synthesis, we select one initial pose from the data set as the input pose and sample several poses as output poses. 

By the way, we have released the training and evaluation code. You can refer to the code for more details.

**Comment by belgacemi** [comment]
Hi @skhu101 , Thank you for sharing the code! Much appreciated!  
Is there a possibility of also releasing the pretrained checkpoints?

**Comment by skhu101** [comment]
Hi, thanks for your interest in our work. Pre-trained checkpoints have been released.
