### ISSUE TITLE
I wonder how to do an inference on my own data?

### ISSUE THREAD

**Issue by Alex-ChaoBo** [skhu101/SHERF#9]

**Comment by skhu101** [comment]
Hello, thanks for your interest in our work. One fast way is to put data in the same format as our RenderPeople data folder. Then you can use the RenderPeopleDatasetBatch function in RenderPeople_dataset.py to load your own data for the novel view and novel pose inference. I will upload the RenderPeople dataset soon.

**Comment by skhu101** [comment]
Hi, just let you know we have released rendered multi-view images from RenderPeople asset.

**Comment by Alex-ChaoBo** [comment]
Thanks a lot! This will be very helpful! really appreciate your work
